logger:
  level: "INFO"
  consol_active: yes
  file_active: yes
  file_path: "./log/test.log"

simulation:
  loops_per_run: 1000
  snapshot_interval: 1000
  stats_interval: 1
  draw_interval: 100
  max_threads: 16


simulations:
  #Rule Checks
  ba_10a_100n_p8_d2_xl:
    sim_3:
      nodes: 100

    default:
      nodes: 100
      graph:
        generator_function:
          name: "barabasi_albert"
          options:
            m: 1
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
        distribution_function:
          name: "random"
      rules:
        - name: "dynamic_ad"
        - name: "social_desirability"
          options:
            p: 0.08
            d: 0.02
      stats:
        active:
          - "number_of_edges"
          - "number_of_nodes"
          - "average_orientation"
          - "graph_density"
          - "graph_transitivity"
  ba_10a_100n_p4_d8_xl:
    sim_3:
      nodes: 100

    default:
      nodes: 100
      graph:
        generator_function:
          name: "barabasi_albert"
          options:
            m: 1
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
        distribution_function:
          name: "random"
      rules:
        - name: "dynamic_ad"
        - name: "social_desirability"
          options:
            p: 0.04
            d: 0.08
      stats:
        active:
          - "number_of_edges"
          - "number_of_nodes"
          - "average_orientation"
          - "graph_density"
          - "graph_transitivity"
