logger:
  level: "INFO"
  consol_active: yes
  file_active: yes
  file_path: "./log/test.log"

simulation:
  loops_per_run: 1000
  snapshot_interval: 1000
  stats_interval: 1
  draw_interval: 100
  max_threads: 16


simulations:
  #Rule Checks
  rule_check:
    sim_1:
      rules:
        - name: "association"
        - name: "disassociation"
    sim_2:
      rules:
        - name: "dynamic_ad"
    sim_3:
      rules:
        - name: "association"
        - name: "disassociation"
        - name: "social_desirability"
          options:
            p: 0.6
            d: 0.0
    sim_4:
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
            social_disirebility:
              p: 0.6
              d: 0.0
        distribution_function:
          name: "random"
          options:
            n: 5
      rules:
        - name: "dynamic_ad"

    default:
      nodes: 100
      graph:
        generator_function:
          name: "barabasi_albert"
          options:
            m: 1
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
        distribution_function:
          name: "random"
          options:
            n: 5
      rules:
        - name: "association"
        - name: "disassociation"
      stats:
        active:
          - "number_of_edges"
          - "number_of_nodes"
          - "average_orientation"
          - "graph_density"
          - "graph_transitivity"
  #Diviation checks
  check_for_diviation_r_ba_1:
    sim_1:
      nodes: 500
    sim_2:
      nodes: 500
    sim_3:
      nodes: 500
    sim_4:
      nodes: 500
    sim_5:
      nodes: 500
    sim_6:
      nodes: 500
    sim_7:
      nodes: 500
    sim_8:
      nodes: 500
    sim_9:
      nodes: 500
    sim_10:
      nodes: 500
    sim_11:
      nodes: 500
    sim_12:
      nodes: 500
    default:
      nodes: 500
      graph:
        generator_function:
          name: "barabasi_albert"
          options:
            m: 1
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
        distribution_function:
          name: "random"
          options:
            n: 5
      rules:
        - name: "association"
        - name: "disassociation"
      stats:
        active:
          - "number_of_edges"
          - "number_of_nodes"
          - "average_orientation"
          - "graph_density"
          - "graph_transitivity"

  check_for_diviation_r_ba_2:
    sim_1:
      nodes: 500
    sim_2:
      nodes: 500
    sim_3:
      nodes: 500
    sim_4:
      nodes: 500
    sim_5:
      nodes: 500
    sim_6:
      nodes: 500
    sim_7:
      nodes: 500
    sim_8:
      nodes: 500
    sim_9:
      nodes: 500
    sim_10:
      nodes: 500
    sim_11:
      nodes: 500
    sim_12:
      nodes: 500
    default:
      nodes: 500
      graph:
        generator_function:
          name: "barabasi_albert"
          options:
            m: 2
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
        distribution_function:
          name: "random"
          options:
            n: 5
      rules:
        - name: "association"
        - name: "disassociation"
      stats:
        active:
          - "number_of_edges"
          - "number_of_nodes"
          - "average_orientation"
          - "graph_density"
          - "graph_transitivity"

  group_random_barabasi_expo_1:
    sim_1:
      nodes: 10
    sim_2:
      nodes: 100
    sim_3:
      nodes: 1000
    sim_4:
      nodes: 10000
    default:
      nodes: 10
      graph:
        generator_function:
          name: "barabasi_albert"
          options:
            m: 1
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
        distribution_function:
          name: "random"
          options:
           n: 5
      rules:
        - name: "association"
        - name: "disassociation"
      stats:
        active:
          - "number_of_edges"
          - "number_of_nodes"
          - "average_orientation"
          - "graph_density"
          - "graph_transitivity"
#
  group_random_barabasi_expo_2:
    sim_1:
      nodes: 10
    sim_2:
      nodes: 100
    sim_3:
      nodes: 1000
    sim_4:
      nodes: 10000
    default:
      nodes: 10
      graph:
        generator_function:
          name: "barabasi_albert"
          options:
            m: 2
      actor:
        generator_function:
          name: "random"
          options:
            n:  10
        distribution_function:
          name: "random"
          options:
           n: 5
      rules:
        - name: "association"
        - name: "disassociation"
      stats:
        active:
          - "number_of_edges"
          - "number_of_nodes"
          - "average_orientation"
          - "graph_density"
          - "graph_transitivity"